# RNN 구현 
- 파이썬 코드로 RNN 구현하기 : Do it 딥러닝 입문 

In [ ]:
import numpy as np 

In [ ]:

class RecurrentNetwork:

    def __init__(self, n_cells = 10, batch_size = 32, learning_rate=0.1):

        self.n_cells = n_cells
        self.batch_size = batch_size
        self.learning_rate = learning_rate 

        self.w1h = None # 은닉 상태 가중치 
        self.w1x = None # 입력에 대한 가중치 
        self.b1 = None # 순환층 절편 
        self.w2 = None # 출력층 가중치 
        self.b2 = None # 출력층 절편 
        self.h = None # 순환층 활성화 출력 
        self.losses = [] # 훈련 손실 
        self.val_losses = [] # 검증 손실 
        
    # 순전파 알고리즘 
    def forpass(self, x):
        
        # 은닉 상태 초기화 
        # - 여기서 들어오는 x는 3차원 배열 (샘플수, 행, 열)
        # - x.shape[0]은 샘플 수
        # - cell 수 만큼 0으로 채워진 배열이 샘플 수 만큼 들어있는 배열 만듦 
        self.h = [np.zeros((x.shape[0], self.n_cells))] 
        
        # 배치 차원과 타임 스텝 차원 바꾸기 
        # - x array의 3차원 축과 2차원 축을 바꿔라 (행렬에서 차원은 열을 말함) 
        seq = np.swapaxes(x, 0, 1) 
        
        # 순환층 선형식 계산하기 
        # - 여기서 x가 단어 하나가 들어오는 건지, 하나의 샘플(문장) 에 있는 단어들의 행렬이 들어오는 건지 모르겠음 
        for x in seq : 
            # 입력 가중치, hidden state, 절편 
            z1 = np.dot(x, self.w1x) + np.dot(self.h[-1], self.w1h) + self.b1  
            h = np.tanh(z1) # 활성화 함수 출력값 
            self.h.append(h) # 은닉 상태 저장 

            # 출력청 선형식 계산 
            z2 = np.dot(h, self.w2) + self.b2 
        
        return z2 # 순전파 출력값 리턴 

    # 역전파 알고리즘 
    # - 출력값과 손실 계산하여 가중치 조정 
    def backprop(self, x, err) : 
        m = len(x) # 샘플 갯수 

        # 출력층의 가중치와 절편에 대한 그레디언트 계산 
        w2_grad = np.dot(self.h[-1].T, err) / m 
        b2_grad = np.sum(err) / m

        seq = np.swapaxes(x, 0, 1)

        w1h_grad = w1x_grad = b1_grad = 0 
        # 셀 직전까지 그레디언트 계산 
        err_to_cell = np.dot(err, self.w2.T) * (1 - self.h[-1] ** 2)
        # ahems xkdla tmxpq rjtmffjtj rmfpeldjsxm wjsvk 
    

In [5]:
import numpy as np 
test = [np.zeros((1,1))]
print(test)

[array([[0.]])]


In [7]:
np.zeros((2,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
a = [[[1,2,3],[7,8,9]]]
a_swapped = np.swapaxes(a, 0, 1)
a_swapped

array([[[1, 2, 3]],

       [[7, 8, 9]]])

In [30]:
arr = np.array(a)

In [31]:
arr

array([[[1, 2, 3],
        [7, 8, 9]]])

In [32]:
arr.shape

(1, 2, 3)

In [33]:
len(arr)

1

In [34]:
arr = [...]
arr

[Ellipsis]